apiVersion: image.toolkit.fluxcd.io/v1beta2
kind: ImageRepository
metadata:
  name: {{ .Values.applicationName }}
  namespace: flux-system
spec:
  image: {{ .Values.image.repository }}
  interval: 5m0s
